# MultiSignBook
settings:
  max_signatures: 8

# Сообщения
# Используйте "§" для установки цвета в чате
messages:
  book_locked: "§cЭта книга уже защищена от подписей."
  book_already_signed: "§cВы уже подписались в этой книге."
  book_max_signatures: "§cКнига уже содержит максимальное количество подписей"
  book_protected: "§aКнига успешно защищена от подписей."
  signature_added: "§aПодпись успешно добавлена."
  book_locked_cannot_sign: "§cЭту книгу нельзя подписать, она защищена от подписей."
  invalid_command: "§cИспользуйте /sign lock для защиты от подписей или /sign s для добавления подписи."
  not_signed_book: "§cДля выполнения команд /sign возьмите в руки подписаную книгу."
  invalid_command_console: "§cНеверная команда. Используйте /sign lock или /sign s."

# Заголовки для лора в книге
# Не рекомендуется изменять если книги на сервере были подписаны, это может их сломать.
lore:
  locked: "§cЗащищено: "
  signed: "§7Подписано: "
