name: MultiSignBook
version: 1.0
main: org.tokishu.multisignbook.multisignbook.MultiSignBook
api-version: 1.20
description: Your plugin description
author: YourName
commands:
  sign:
    description: Main command for signing books
    usage: /sign <lock|s>
  showSignatures:
    description: Admin command
    usage: /showSignatures